"""add quote versioning columns

Revision ID: 0f2eb0e47aa2
Revises: bba96b45f5bf
Create Date: 2026-06-06 02:21:05.558359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f2eb0e47aa2'
down_revision: Union[str, Sequence[str], None] = 'bba96b45f5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('member_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('worker_type', sa.String(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_assignments_project', 'project_assignments', ['project_id', 'removed_at'], unique=False)
    op.create_index(op.f('ix_project_assignments_project_id'), 'project_assignments', ['project_id'], unique=False)
    op.create_table('project_guests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_guests_owner_id'), 'project_guests', ['owner_id'], unique=False)
    op.create_index(op.f('ix_project_guests_project_id'), 'project_guests', ['project_id'], unique=False)
    op.create_table('safety_briefings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('site_label', sa.String(), nullable=True),
    sa.Column('animator', sa.String(), nullable=True),
    sa.Column('signed_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('briefing_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_safety_briefings_status', 'safety_briefings', ['status', 'deleted_at'], unique=False)
    op.create_table('subcontractor_situations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subcontractor_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontractor_situations_project_id'), 'subcontractor_situations', ['project_id'], unique=False)
    op.create_index(op.f('ix_subcontractor_situations_subcontractor_id'), 'subcontractor_situations', ['subcontractor_id'], unique=False)
    op.create_table('warranties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warranties_project_id'), 'warranties', ['project_id'], unique=False)
    op.create_table('document_signature_otps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('requested_ip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_signature_otps_document_id'), 'document_signature_otps', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_signature_otps_user_id'), 'document_signature_otps', ['user_id'], unique=False)
    op.create_index('ix_signature_otps_user_doc', 'document_signature_otps', ['user_id', 'document_id', 'consumed_at'], unique=False)
    op.create_table('document_signatures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('signer_id', sa.String(), nullable=False),
    sa.Column('document_hash', sa.String(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('audit_meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['signer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_signatures_document_id'), 'document_signatures', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_signatures_signer_id'), 'document_signatures', ['signer_id'], unique=False)
    op.create_index('ix_signatures_signer', 'document_signatures', ['signer_id', 'signed_at'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('project_label', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('lines', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('converted_invoice_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('version_note', sa.Text(), nullable=True),
    sa.Column('parent_quote_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['converted_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['parent_quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    op.create_index('ix_quotes_status_deleted', 'quotes', ['status', 'deleted_at'], unique=False)
    op.create_index('ix_activity_actor_created', 'activity_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_activity_entity', 'activity_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_appointments_start', 'appointments', ['start_time', 'status', 'deleted_at'], unique=False)
    op.create_index('ix_attendance_worker_date', 'attendance', ['worker_id', 'date'], unique=False)
    op.add_column('cms_site_settings', sa.Column('rc_number', sa.String(), nullable=True))
    op.add_column('cms_site_settings', sa.Column('tax_id', sa.String(), nullable=True))
    op.add_column('cms_site_settings', sa.Column('vat_rate', sa.Float(), nullable=True))
    op.add_column('cms_site_settings', sa.Column('role_permissions', sa.JSON(), nullable=True))
    op.add_column('cms_site_settings', sa.Column('default_currency', sa.String(), nullable=True))
    op.add_column('cms_site_settings', sa.Column('fiscal_year', sa.String(), nullable=True))
    op.add_column('cms_site_settings', sa.Column('system_language', sa.String(), nullable=True))
    op.add_column('cms_site_settings', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('cms_site_settings', sa.Column('date_format', sa.String(), nullable=True))
    op.add_column('cms_site_settings', sa.Column('session_timeout', sa.String(), nullable=True))
    op.add_column('cms_site_settings', sa.Column('email_notifications', sa.Boolean(), nullable=True))
    op.add_column('cms_site_settings', sa.Column('enforce_2fa', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('version_note', sa.Text(), nullable=True))
    op.create_index('ix_documents_project_category', 'documents', ['project_id', 'category', 'deleted_at'], unique=False)
    op.create_index('ix_documents_signed', 'documents', ['signed_at', 'shared_with_client'], unique=False)
    op.create_index('ix_invoices_client_status', 'invoices', ['client_id', 'status', 'deleted_at'], unique=False)
    op.create_index('ix_invoices_project_status', 'invoices', ['project_id', 'status', 'deleted_at'], unique=False)
    op.create_index('ix_invoices_status_due', 'invoices', ['status', 'due_date', 'deleted_at'], unique=False)
    op.create_index('ix_leads_status_created', 'leads', ['status', 'created_at', 'deleted_at'], unique=False)
    op.create_index('ix_messages_conv_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index('ix_payroll_period_status', 'payroll', ['period', 'status'], unique=False)
    op.create_index('ix_planning_project_dates', 'planning_tasks', ['project_id', 'start_date', 'deleted_at'], unique=False)
    op.create_index('ix_projects_client', 'projects', ['client_id', 'deleted_at'], unique=False)
    op.create_index('ix_projects_status_deleted', 'projects', ['status', 'deleted_at'], unique=False)
    op.create_index('ix_pr_status', 'purchase_requests', ['status', 'deleted_at'], unique=False)
    op.add_column('sav_tickets', sa.Column('rating_comment', sa.Text(), nullable=True))
    op.create_index('ix_sav_client_status', 'sav_tickets', ['client_id', 'status', 'deleted_at'], unique=False)
    op.create_index('ix_sav_project_status', 'sav_tickets', ['project_id', 'status', 'deleted_at'], unique=False)
    op.create_index('ix_sub_invoices_status_due', 'subcontractor_invoices', ['status', 'due_date', 'deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sub_invoices_status_due', table_name='subcontractor_invoices')
    op.drop_index('ix_sav_project_status', table_name='sav_tickets')
    op.drop_index('ix_sav_client_status', table_name='sav_tickets')
    op.drop_column('sav_tickets', 'rating_comment')
    op.drop_index('ix_pr_status', table_name='purchase_requests')
    op.drop_index('ix_projects_status_deleted', table_name='projects')
    op.drop_index('ix_projects_client', table_name='projects')
    op.drop_index('ix_planning_project_dates', table_name='planning_tasks')
    op.drop_index('ix_payroll_period_status', table_name='payroll')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index('ix_messages_conv_created', table_name='messages')
    op.drop_index('ix_leads_status_created', table_name='leads')
    op.drop_index('ix_invoices_status_due', table_name='invoices')
    op.drop_index('ix_invoices_project_status', table_name='invoices')
    op.drop_index('ix_invoices_client_status', table_name='invoices')
    op.drop_index('ix_documents_signed', table_name='documents')
    op.drop_index('ix_documents_project_category', table_name='documents')
    op.drop_column('documents', 'version_note')
    op.drop_column('cms_site_settings', 'enforce_2fa')
    op.drop_column('cms_site_settings', 'email_notifications')
    op.drop_column('cms_site_settings', 'session_timeout')
    op.drop_column('cms_site_settings', 'date_format')
    op.drop_column('cms_site_settings', 'timezone')
    op.drop_column('cms_site_settings', 'system_language')
    op.drop_column('cms_site_settings', 'fiscal_year')
    op.drop_column('cms_site_settings', 'default_currency')
    op.drop_column('cms_site_settings', 'role_permissions')
    op.drop_column('cms_site_settings', 'vat_rate')
    op.drop_column('cms_site_settings', 'tax_id')
    op.drop_column('cms_site_settings', 'rc_number')
    op.drop_index('ix_attendance_worker_date', table_name='attendance')
    op.drop_index('ix_appointments_start', table_name='appointments')
    op.drop_index('ix_activity_entity', table_name='activity_logs')
    op.drop_index('ix_activity_actor_created', table_name='activity_logs')
    op.drop_index('ix_quotes_status_deleted', table_name='quotes')
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('ix_signatures_signer', table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_signer_id'), table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_document_id'), table_name='document_signatures')
    op.drop_table('document_signatures')
    op.drop_index('ix_signature_otps_user_doc', table_name='document_signature_otps')
    op.drop_index(op.f('ix_document_signature_otps_user_id'), table_name='document_signature_otps')
    op.drop_index(op.f('ix_document_signature_otps_document_id'), table_name='document_signature_otps')
    op.drop_table('document_signature_otps')
    op.drop_index(op.f('ix_warranties_project_id'), table_name='warranties')
    op.drop_table('warranties')
    op.drop_index(op.f('ix_subcontractor_situations_subcontractor_id'), table_name='subcontractor_situations')
    op.drop_index(op.f('ix_subcontractor_situations_project_id'), table_name='subcontractor_situations')
    op.drop_table('subcontractor_situations')
    op.drop_index('ix_safety_briefings_status', table_name='safety_briefings')
    op.drop_table('safety_briefings')
    op.drop_index(op.f('ix_project_guests_project_id'), table_name='project_guests')
    op.drop_index(op.f('ix_project_guests_owner_id'), table_name='project_guests')
    op.drop_table('project_guests')
    op.drop_index(op.f('ix_project_assignments_project_id'), table_name='project_assignments')
    op.drop_index('ix_project_assignments_project', table_name='project_assignments')
    op.drop_table('project_assignments')
    # ### end Alembic commands ###
