"""add storage_key to erp models

Revision ID: 1bcb56f304b4
Revises: 8e90643e5252
Create Date: 2026-06-06 04:34:16.171697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1bcb56f304b4'
down_revision: Union[str, Sequence[str], None] = '8e90643e5252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_key', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('storage_key', sa.String(), nullable=True))
    op.add_column('project_media', sa.Column('storage_key', sa.String(), nullable=True))
    op.add_column('quotes', sa.Column('storage_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'storage_key')
    op.drop_column('project_media', 'storage_key')
    op.drop_column('invoices', 'storage_key')
    op.drop_column('documents', 'storage_key')
    # ### end Alembic commands ###
