"""Seed part 2 — Services, Projects, Blog, FAQ, Legal pages."""
from app.database import AsyncSessionLocal
from app.models.cms import CMSService, CMSProject, CMSBlogPost, CMSFaqCategory, CMSFaqItem, CMSLegalPage

IMG = "https://images.unsplash.com/photo-"

async def seed_part2():
    async with AsyncSessionLocal() as db:
        # ── Services ──────────────────────────────────────────
        svcs = [
          dict(id="svc-1",slug="construction-batiments",title="Construction de Bâtiments",subtitle="Résidentiel & Commercial",
            desc="Nous réalisons des constructions neuves de haute qualité, allant des villas de standing aux complexes commerciaux et industriels.",
            icon_key="BuildingIcon",image=f"{IMG}1541888086425-d81bb19240f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80",
            images=[f"{IMG}1541888086425-d81bb19240f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",f"{IMG}1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",f"{IMG}1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",f"{IMG}1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"],
            details="Grâce à notre expertise technique et notre réseau de partenaires fiables, nous utilisons des matériaux de première qualité respectant les normes environnementales et de sécurité les plus strictes.",
            benefits=["Respect strict des délais annoncés","Assurance décennale incluse","Matériaux certifiés et durables","Un seul interlocuteur dédié","Suivi de chantier transparent","Respect des normes parasismiques"],
            related_category="Résidentiel",
            process_steps=[{"title":"Étude & Planification","desc":"Analyse du terrain, étude de sol, élaboration des plans et obtention des permis de construire.","iconKey":"ClipboardListIcon"},{"title":"Gros Œuvre","desc":"Terrassement, fondations, élévation des murs porteurs, dalles et charpente.","iconKey":"HardHatIcon"},{"title":"Second Œuvre & Finitions","desc":"Plomberie, électricité, isolation, revêtements de sol, peinture et menuiseries.","iconKey":"ShieldCheckIcon"},{"title":"Livraison Clé en Main","desc":"Inspection finale, levée des réserves, remise des clés et du dossier technique complet.","iconKey":"KeyIcon"}],
            faq=[{"q":"Combien de temps dure la construction d'une maison ?","a":"La durée varie selon la taille et la complexité. En moyenne, 10 à 18 mois pour une villa R+1 à R+2."},{"q":"Quelles garanties offrez-vous ?","a":"Garantie de parfait achèvement (1 an), garantie biennale (2 ans), et garantie décennale (10 ans)."},{"q":"Puis-je suivre l'avancement en temps réel ?","a":"Chaque client dispose d'un accès à notre plateforme de suivi de chantier."},{"q":"Fournissez-vous les matériaux ?","a":"Nous gérons l'intégralité de l'approvisionnement en matériaux."}],
            sort_order=0),
          dict(id="svc-2",slug="conception-architecturale",title="Conception Architecturale",subtitle="Plans 2D/3D & Design",
            desc="Notre bureau d'études transforme vos idées en plans concrets avec des modélisations 3D réalistes.",
            icon_key="PencilRulerIcon",image=f"{IMG}1503387762-592deb58ef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80",
            images=[f"{IMG}1503387762-592deb58ef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",f"{IMG}1574958269340-fa927503f3dd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",f"{IMG}1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",f"{IMG}1600607687939-ce8a6c25118c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"],
            details="Nous utilisons les derniers logiciels de CAO/DAO (AutoCAD, Revit) pour vous fournir des plans détaillés et des modélisations 3D immersives.",
            benefits=["Modélisation 3D réaliste","Optimisation des espaces","Dossier de permis complet","Respect des normes d'urbanisme","Design sur-mesure","Étude d'impact environnemental"],
            related_category="Commercial",
            process_steps=[{"title":"Consultation & Brief","desc":"Rencontre avec le client pour comprendre ses besoins.","iconKey":"SearchIcon"},{"title":"Esquisse & Avant-Projet","desc":"Création des premières esquisses et plans de masse.","iconKey":"PencilRulerIcon"},{"title":"Modélisation 3D","desc":"Développement complet des plans d'exécution et modélisation 3D.","iconKey":"LayersIcon"},{"title":"Dossier Administratif","desc":"Constitution et dépôt du dossier de permis de construire.","iconKey":"FileTextIcon"}],
            faq=[{"q":"Puis-je voir mon projet en 3D ?","a":"Oui, nous réalisons des modélisations 3D photoréalistes et des visites virtuelles."},{"q":"Combien coûte une étude architecturale ?","a":"Entre 8% et 12% du coût total de la construction."},{"q":"Gérez-vous les démarches de permis ?","a":"Oui, nous constituons l'intégralité du dossier."}],
            sort_order=1),
          dict(id="svc-3",slug="genie-civil",title="Génie Civil & Travaux Publics",subtitle="Infrastructures complexes",
            desc="Expertise pointue pour les infrastructures lourdes, routes, ponts et aménagements urbains.",
            icon_key="HardHatIcon",image=f"{IMG}1581094794329-c8112a89af12?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80",
            images=[f"{IMG}1581094794329-c8112a89af12?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",f"{IMG}1504307651254-35680f356dfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",f"{IMG}1582063289852-62e3ba2747f8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",f"{IMG}1590725121839-892b458a74fe?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"],
            details="Nos équipes d'ingénieurs en génie civil déploient tout leur savoir-faire pour garantir des ouvrages d'art capables de résister à l'épreuve du temps.",
            benefits=["Expertise technique reconnue","Parc matériel de pointe","Solutions innovantes de soutènement","Gestion stricte des normes HSE","Études géotechniques approfondies","Respect des normes environnementales"],
            related_category="Public",
            process_steps=[{"title":"Études Géotechniques","desc":"Analyse approfondie du sol et évaluation des risques.","iconKey":"ScanIcon"},{"title":"Mobilisation & Terrassement","desc":"Déploiement du parc matériel lourd sur site.","iconKey":"TruckIcon"},{"title":"Exécution des Ouvrages","desc":"Réalisation des fondations profondes et structures.","iconKey":"HardHatIcon"},{"title":"Réception & Contrôle","desc":"Tests de charge et essais de conformité.","iconKey":"ShieldCheckIcon"}],
            faq=[{"q":"Quels types d'infrastructures réalisez-vous ?","a":"Routes, ponts, réseaux d'assainissement, fondations spéciales, murs de soutènement."},{"q":"Disposez-vous de votre propre parc matériel ?","a":"Oui, pelles hydrauliques, bulldozers, grues, bétonnières, compacteurs."},{"q":"Comment gérez-vous la sécurité ?","a":"Chaque chantier dispose d'un responsable HSE dédié."}],
            sort_order=2),
          dict(id="svc-4",slug="renovation-amenagement",title="Rénovation et Aménagement",subtitle="Réhabilitation & Second Œuvre",
            desc="Rénovation lourde et réhabilitation de bâtiments anciens, alliant respect du patrimoine et modernité.",
            icon_key="PaintRollerIcon",image=f"{IMG}1504307651254-35680f356dfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80",
            images=[f"{IMG}1581094794329-c8112a89af12?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",f"{IMG}1504307651254-35680f356dfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"],
            details="De la démolition sélective à la finition intérieure, nous repensons vos espaces.",
            benefits=["Mise aux normes électriques","Isolation thermique RT2020","Aménagement sur-mesure","Respect de l'architecture d'origine","Valorisation du patrimoine","Solutions d'extension"],
            related_category="Résidentiel",
            process_steps=[{"title":"Diagnostic","desc":"Inspection complète du bâtiment existant.","iconKey":"SearchIcon"},{"title":"Démolition & Préparation","desc":"Démolition sélective des éléments à remplacer.","iconKey":"HammerIcon"},{"title":"Travaux de Rénovation","desc":"Réfection des réseaux et mise en conformité.","iconKey":"PaintRollerIcon"},{"title":"Finitions","desc":"Revêtements, peinture et aménagement final.","iconKey":"RulerIcon"}],
            faq=[{"q":"Faut-il un permis pour une rénovation ?","a":"Cela dépend de l'ampleur des travaux."},{"q":"Combien coûte une rénovation au m² ?","a":"Entre 800 et 1500 €/m² selon l'état initial."},{"q":"Peut-on habiter pendant les travaux ?","a":"Pour une rénovation partielle, oui."}],
            sort_order=3),
        ]
        for s in svcs:
            db.add(CMSService(**s))

        # ── Projects ──────────────────────────────────────────
        projs = [
          dict(id="prj-1",slug="villa-alizes",title="Villa Contemporaine Les Alizés",category="Résidentiel",status="Livré en 2023",location="Douala, Bonapriso",client_name="Privé",area="450 m² (R+2)",duration="14 mois",architect="Cabinet Design & Co",description="Villa moderne R+2 avec piscine, jardin paysager et finitions haut de gamme.",images=[f"{IMG}1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80",f"{IMG}1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80",f"{IMG}1600607687939-ce8a6c25118c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80"],challenge="Topographie complexe avec forte déclivité.",solution="Fondations spéciales sur pieux, grandes baies vitrées orientées stratégiquement.",video_url="https://www.youtube.com/embed/ScMzIvxBSi4",progression=[{"step":"Études et conception","status":"validé","date":"Janvier 2022"},{"step":"Terrassement et fondations","status":"validé","date":"Mars 2022"},{"step":"Gros œuvre","status":"validé","date":"Juillet 2022"},{"step":"Mise hors d'eau / hors d'air","status":"validé","date":"Octobre 2022"},{"step":"Second œuvre et finitions","status":"validé","date":"Février 2023"},{"step":"Aménagements extérieurs","status":"validé","date":"Avril 2023"},{"step":"Livraison","status":"validé","date":"Mai 2023"}],progress=100,featured=True,sort_order=0),
          dict(id="prj-2",slug="complexe-horizon",title="Complexe Bureaux Horizon",category="Commercial",status="Livré en 2022",location="Yaoundé, Centre",client_name="Horizon Invest",area="2500 m² (R+6)",duration="24 mois",architect="Studio ArchiPlus",description="Immeuble de bureaux R+6 certifié HQE avec façade bioclimatique.",images=[f"{IMG}1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80",f"{IMG}1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80"],challenge="Construction en centre-ville avec espace restreint.",solution="Logistique en flux tendu et structures métalliques préfabriquées.",video_url="https://www.youtube.com/embed/ScMzIvxBSi4",progression=[{"step":"Permis de construire","status":"validé","date":"Février 2020"},{"step":"Fondations profondes","status":"validé","date":"Juin 2020"},{"step":"Élévation de la structure","status":"validé","date":"Décembre 2020"},{"step":"Façades et vitrages","status":"validé","date":"Août 2021"},{"step":"Aménagements intérieurs","status":"validé","date":"Janvier 2022"},{"step":"Tests et mise en service","status":"validé","date":"Mars 2022"},{"step":"Inauguration","status":"validé","date":"Avril 2022"}],progress=100,sort_order=1),
          dict(id="prj-3",slug="hopital-regional",title="Hôpital Régional de Bafoussam",category="Institutionnel",status="En Cours",location="Bafoussam",client_name="Ministère de la Santé Publique",area="8500 m²",duration="36 mois",architect="Santé Design Architecture",description="Centre hospitalier de 120 lits avec bloc opératoire.",images=[f"{IMG}1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80"],challenge="Intégration complexe des fluides médicaux.",solution="Utilisation de la modélisation BIM pour coordonner les réseaux techniques.",video_url="https://www.youtube.com/embed/ScMzIvxBSi4",progression=[{"step":"Terrassement","status":"validé","date":"Mai 2023"},{"step":"Structure principale","status":"validé","date":"Novembre 2023"},{"step":"Réseaux et fluides médicaux","status":"en-cours"},{"step":"Aménagements intérieurs","status":"à-venir"},{"step":"Équipements biomédicaux","status":"à-venir"},{"step":"Tests de conformité","status":"à-venir"}],progress=65,sort_order=2),
          dict(id="prj-4",slug="tour-zenith",title="Fondations Tour Zenith",category="Commercial",status="En Cours",location="Douala, Akwa",client_name="Zenith Corporation",area="12000 m² (R+15)",duration="28 mois",architect="Cabinet Skyline",description="Tour de bureaux de 15 étages avec parking souterrain.",images=[f"{IMG}1504307651254-35680f356dfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80"],challenge="Sol marécageux nécessitant des ancrages profonds.",solution="Fondations sur pieux forés à plus de 30 mètres de profondeur.",video_url="https://www.youtube.com/embed/ScMzIvxBSi4",progression=[{"step":"Études géotechniques","status":"validé","date":"Septembre 2023"},{"step":"Parois moulées","status":"validé","date":"Décembre 2023"},{"step":"Fondations profondes","status":"en-cours"},{"step":"Radiers et sous-sols","status":"à-venir"},{"step":"Élévation","status":"à-venir"}],progress=45,is_ongoing=True,ongoing_description="Nous avons réalisé la construction complète de ce centre commercial moderne, comprenant 45 boutiques, un food court et un parking souterrain de 500 places.",sort_order=3),
          dict(id="prj-5",slug="boutique-flagship",title="Centre Commercial de la Place",category="Commercial",status="En Cours",location="Douala, Bonanjo",client_name="Retail Group Africa",area="18000 m²",duration="22 mois",architect="Espaces & Commerce",description="Un centre commercial moderne avec 45 boutiques.",images=[f"{IMG}1582063289852-62e3ba2747f8?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80"],challenge="Espace commercial attractif avec solutions éco-responsables.",solution="Verrière centrale monumentale et système de récupération de chaleur.",video_url="https://www.youtube.com/embed/ScMzIvxBSi4",progression=[{"step":"Gros œuvre","status":"validé","date":"Octobre 2023"},{"step":"Couverture et verrière","status":"validé","date":"Janvier 2024"},{"step":"Aménagement cellules","status":"en-cours"},{"step":"Finitions espaces communs","status":"à-venir"},{"step":"Installation équipements","status":"à-venir"}],progress=50,sort_order=4),
          dict(id="prj-6",slug="residence-jardins",title="Complexe Résidentiel Les Jardins",category="Résidentiel",status="En Cours",location="Kribi",client_name="Promoteur Immobilier Sud",area="3 hectares",duration="30 mois",architect="Eco-Habitat Architectes",description="Ensemble résidentiel de 200 appartements avec espaces verts.",images=[f"{IMG}1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80"],challenge="Matériaux résistants à la corrosion saline.",solution="Bétons spéciaux et système de drainage écologique.",video_url="https://www.youtube.com/embed/ScMzIvxBSi4",progression=[{"step":"Viabilisation","status":"validé","date":"Août 2023"},{"step":"Fondations blocs A et B","status":"validé","date":"Novembre 2023"},{"step":"Élévation","status":"validé","date":"Février 2024"},{"step":"Second œuvre","status":"en-cours"},{"step":"Espaces verts","status":"à-venir"},{"step":"Livraison","status":"à-venir"}],progress=70,sort_order=5),
          dict(id="prj-7",slug="pont-wouri",title="Réhabilitation Pont du Wouri",category="Institutionnel",status="En Cours",location="Douala",client_name="Ministère des Travaux Publics",area="1.8 km",duration="18 mois",architect="Globus Ingénierie Civile",description="Renforcement structurel et élargissement du tablier.",images=[f"{IMG}1541888086425-d81bb19240f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80"],challenge="Renforcer sans interrompre le trafic.",solution="Travaux de nuit et fibres de carbone pour le renforcement.",video_url="https://www.youtube.com/embed/ScMzIvxBSi4",progression=[{"step":"Inspection","status":"validé","date":"Juin 2023"},{"step":"Renforcement piles","status":"validé","date":"Octobre 2023"},{"step":"Réparation tablier","status":"validé","date":"Janvier 2024"},{"step":"Nouveau revêtement","status":"en-cours"},{"step":"Éclairage","status":"à-venir"}],progress=80,sort_order=6),
          dict(id="prj-8",slug="villa-moderne",title="Villa Moderne R+1 Bastos",category="Résidentiel",status="En Cours",location="Yaoundé, Bastos",client_name="Privé",area="600 m²",duration="12 mois",architect="Studio ArchiPlus",description="Villa contemporaine avec toiture végétalisée et domotique.",images=[f"{IMG}1503387762-592deb58ef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80"],challenge="Architecture ultra-contemporaine avec domotique.",solution="Toiture végétalisée et panneaux solaires invisibles.",video_url="https://www.youtube.com/embed/ScMzIvxBSi4",progression=[{"step":"Fondations","status":"validé","date":"Novembre 2023"},{"step":"Élévation R+1","status":"validé","date":"Janvier 2024"},{"step":"Toiture","status":"en-cours"},{"step":"Domotique","status":"à-venir"},{"step":"Finitions","status":"à-venir"}],progress=30,sort_order=7),
          dict(id="prj-9",slug="usine-logistique",title="Entrepôt Logistique Zone Franche",category="Industriel",status="Livré en 2023",location="Douala, Bonabéri",client_name="LogisCam SA",area="5000 m²",duration="10 mois",architect="Globus Engineering",description="Entrepôt de 5000 m² avec quais de chargement.",images=[f"{IMG}1581094794329-c8112a89af12?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80"],challenge="Délais très courts et normes incendie strictes.",solution="Charpente métallique préfabriquée pour assemblage rapide.",video_url="https://www.youtube.com/embed/ScMzIvxBSi4",progression=[{"step":"Terrassement","status":"validé","date":"Février 2023"},{"step":"Montage charpente","status":"validé","date":"Avril 2023"},{"step":"Couverture","status":"validé","date":"Juin 2023"},{"step":"Dallage","status":"validé","date":"Août 2023"},{"step":"Sécurité incendie","status":"validé","date":"Octobre 2023"},{"step":"Livraison","status":"validé","date":"Décembre 2023"}],progress=100,sort_order=8),
          dict(id="prj-default",slug="default",title="Projet de Construction",category="Gros Œuvre",status="En Cours",location="Cameroun",client_name="Confidentiel",area="Sur mesure",duration="En cours",architect="Globus Engineering",description="",images=[f"{IMG}1504307651254-35680f356dfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80"],challenge="Répondre aux exigences techniques du client.",solution="Méthodologie clé en main avec suivi rigoureux.",video_url="https://www.youtube.com/embed/ScMzIvxBSi4",progression=[{"step":"Installation","status":"validé","date":"Septembre 2023"},{"step":"Fondations","status":"validé","date":"Novembre 2023"},{"step":"Élévation RDC","status":"validé","date":"Janvier 2024"},{"step":"Charpente","status":"en-cours"},{"step":"Menuiseries","status":"à-venir"},{"step":"Équipements","status":"à-venir"},{"step":"Finitions","status":"à-venir"}],progress=40,sort_order=99),
        ]
        for p in projs:
            db.add(CMSProject(**p))

        await db.commit()
        print("[OK] Phase 2a seeded: Services, Projects")

    from app.seed_part3 import seed_part3
    await seed_part3()
